"""Consolidate Loan and LoanDecision into CreditApplication

Revision ID: 76bb11dbd835
Revises: b1bad1bab5bf
Create Date: 2026-07-22 19:50:18.137640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76bb11dbd835'
down_revision = 'b1bad1bab5bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_decisions_loan_id'))
        batch_op.drop_index(batch_op.f('ix_loan_decisions_user_id'))

    op.drop_table('loan_decisions')
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_user_id'))

    op.drop_table('loan')
    with op.batch_alter_table('credit_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('emi', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('interest_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_applications', schema=None) as batch_op:
        batch_op.drop_column('interest_rate')
        batch_op.drop_column('emi')
        batch_op.drop_column('loan_amount')

    op.create_table('loan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('loan_amount', sa.FLOAT(), nullable=False),
    sa.Column('emi', sa.FLOAT(), nullable=False),
    sa.Column('interest_rate', sa.FLOAT(), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('purpose', sa.VARCHAR(length=80), nullable=True),
    sa.Column('checking_status', sa.VARCHAR(length=80), nullable=True),
    sa.Column('credit_history', sa.VARCHAR(length=120), nullable=True),
    sa.Column('savings_status', sa.VARCHAR(length=80), nullable=True),
    sa.Column('employment', sa.VARCHAR(length=80), nullable=True),
    sa.Column('installment_rate', sa.INTEGER(), nullable=True),
    sa.Column('personal_status', sa.VARCHAR(length=80), nullable=True),
    sa.Column('other_parties', sa.VARCHAR(length=80), nullable=True),
    sa.Column('residence_since', sa.INTEGER(), nullable=True),
    sa.Column('property_magnitude', sa.VARCHAR(length=80), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('other_payment_plans', sa.VARCHAR(length=80), nullable=True),
    sa.Column('housing', sa.VARCHAR(length=80), nullable=True),
    sa.Column('existing_credits', sa.INTEGER(), nullable=True),
    sa.Column('job', sa.VARCHAR(length=80), nullable=True),
    sa.Column('num_dependents', sa.INTEGER(), nullable=True),
    sa.Column('own_telephone', sa.VARCHAR(length=40), nullable=True),
    sa.Column('foreign_worker', sa.VARCHAR(length=40), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_user_id'), ['user_id'], unique=False)

    op.create_table('loan_decisions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('loan_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('lr_decision', sa.VARCHAR(length=20), nullable=True),
    sa.Column('lr_confidence', sa.FLOAT(), nullable=True),
    sa.Column('lr_good_prob', sa.FLOAT(), nullable=True),
    sa.Column('lr_bad_prob', sa.FLOAT(), nullable=True),
    sa.Column('rf_decision', sa.VARCHAR(length=20), nullable=True),
    sa.Column('rf_confidence', sa.FLOAT(), nullable=True),
    sa.Column('rf_good_prob', sa.FLOAT(), nullable=True),
    sa.Column('rf_bad_prob', sa.FLOAT(), nullable=True),
    sa.Column('final_decision', sa.VARCHAR(length=20), nullable=True),
    sa.Column('consensus', sa.BOOLEAN(), nullable=True),
    sa.Column('lr_shap_reasons', sa.TEXT(), nullable=True),
    sa.Column('rf_shap_reasons', sa.TEXT(), nullable=True),
    sa.Column('shap_reasons', sa.TEXT(), nullable=True),
    sa.Column('input_features', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_decisions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_decisions_loan_id'), ['loan_id'], unique=False)

    # ### end Alembic commands ###
